name: CD - Build & Push Docker

on:
  workflow_dispatch:      # bisa dipicu manual dari tab Actions di GitHub
    inputs:
      run_id:
        description: "MLflow run_id deploy"
        required: true

env:
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install mlflow
        run: pip install mlflow
      
      - name: Validate run_id exists
        run: |
          python -c "
          import mlflow
          run = mlflow.get_run('${{ github.event.inputs.run_id }}')
          print('Run ditemukan:', run.info.run_id)
          print('Status:', run.info.status)
          print('Experiment ID:', run.info.experiment_id)
          "

      - name: Build Docker image from MLflow model
        run: |
          mlflow models build-docker \
            --model-uri "runs:/${{ github.event.inputs.run_id }}/model" \
            --name "${{ secrets.DOCKERHUB_USERNAME }}/workflow-ml"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/workflow-ml-fraud"
